data_buddy_install_root: /usr/local/app/data_buddy
data_buddy_smb_root: '{{ data_buddy_install_root }}/local/network_share'
data_buddy_immich_root: '{{ data_buddy_install_root }}/local/immich'
data_buddy_smb_user: data-buddy
data_buddy_share_name: share 
