_diskless_alpine__root_password: "{{ diskless_alpine__root_password | mandatory }}"

diskless_alpine__disk: /dev/mmcblk0
diskless_alpine__disk_partition: "{{ diskless_alpine__disk }}p1"

diskless_alpine__timezone: America/Chicago
