# TODO: do build from hee
# https://github.com/sensu/sensu-go
# then copy those binaries into image

FROM sensu/sensu:6.13.1

RUN apk add --no-cache tzdata
ENV TZ=America/Chicago

# Reasons:
# curl, jq, yq -> for sensuflow.sh
# nano -> my sanity 
# util-linux -> uuidgen for ntfy-handler
# bind-tools -> dig for DNS monitoring
# figlet -> output formatting
RUN apk add curl jq yq nano util-linux bind-tools figlet


# make symlinks for scripts
RUN ln -s /opt/sensu_scripts/bin/ntfy-send.sh /usr/local/bin/ntfy-send
