services:
  {{ sensu_backend__service_name }}:
    build:
      context: .
      dockerfile: ./Dockerfile-backend
    restart: unless-stopped
    hostname: sensu-backend
    command: >-
      sensu-backend start --state-dir /var/lib/sensu/sensu-backend
    ports:
      - "127.0.0.1:3000:3000"  # Web UI
      - "127.0.0.1:8080:8080"  # API
      - "127.0.0.1:8081:8081"  # Agent communication
    volumes:
      - ./sensu_config:/var/lib/sensu
    environment:
      - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME}
      - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=${SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD}
    networks:
      - sensu

  sensu-proxy:
    image: sensu/sensu:6.11.0
    restart: unless-stopped
    hostname: sensu-proxy-agent
    networks:
      - sensu
    command: >-
      sensu-agent start --config-file /etc/sensu/agent.yml --backend-url ws://sensu-backend:8081
    volumes:
      - ./sensu_proxy_agent.yml:/etc/sensu/agent.yml

  influxdb:
    image: influxdb:2
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
    networks:
      - sensu
    ports:
      - 127.0.0.1:8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - V1_DB_NAME=v1-db
      - V1_RP_NAME=v1-rp
      - V1_AUTH_USERNAME=v1-user
      - TZ=America/Chicago
      - DOCKER_INFLUXDB_INIT_USERNAME=influx_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD={{ sensu_backend__influx_password }}
      - DOCKER_INFLUXDB_INIT_ORG=sensu
      - DOCKER_INFLUXDB_INIT_BUCKET=sensu
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN={{ sensu_backend__influx_admin_token }}

networks:
  sensu:
    driver: bridge
