---
roles:
  - src: staticdev.pyenv
    version: 2.5.1
  - src: gantsign.visual-studio-code
    version: 6.8.0

collections:
  - name: chocolatey.chocolatey
    version: 1.2.0
    source: https://galaxy.ansible.com
  - name: community.general
    version: 5.6.0
    source: https://galaxy.ansible.com
