---
roles:
  - src: staticdev.pyenv
    version: 2.5.1
  - src: gantsign.visual-studio-code
    version: 6.8.0

collections:
  - name: chocolatey.chocolatey
    version: 1.5.3
    source: https://galaxy.ansible.com
  - name: community.general
    version: 12.2.0
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: 1.5.4 # force upgrade ansible.posix
  - name: community.docker
    version: 4.0.0 # force upgrade of community.docker
