- name: Fail Over Multistreamer
  module_defaults:
    ansible.builtin.file:
      owner: root
      group: root
      mode: '0775'
    ansible.builtin.template:
      owner: root
      group: root
      mode: '0775'
    ansible.builtin.copy:
      owner: root
      group: root
      mode: '0775'
  become: true
  block:
    - name: Install requirements
      ansible.builtin.include_tasks: "_{{ ansible_os_family }}_install_requirements.yml"
    - name: Setup server
      ansible.builtin.include_role:
        name: multistream_server
      vars:
        multistream_server_allowed_publishers: '{{ multistream_fail_over__allowed_ips }}'
        multistream_pushes: [] # don't push from nginx
        multistream_execs:
          - '/var/scripts/exec_wrapper.sh $name'
        multistream_server_allowed_play: '{{ multistream_fail_over__allowed_play }}'
    - name: Ensure script dir exists
      ansible.builtin.file:
        path: /var/scripts
        state: directory
        owner: root
        group: root
        mode: '0775'
    - name: Setup wrapper script
      ansible.builtin.copy:
        dest: /var/scripts/exec_wrapper.sh
        content: |
          #!/bin/bash

          on_die() {
          # kill all children
          kill $(jobs -p)
          exit
          }

          trap 'on_die' TERM SIGTERM
          /usr/local/bin/multistream-fail-over 2>&1 | tee /var/log/multistream
          wait
        force: true

    - name: Setup service
      notify:
        - Restart service 
        - Reload service daemon
      ansible.builtin.copy:
        dest: /etc/systemd/system/{{ multistream_fail_over__service_name }}.service
        src: multistream-ip-routes.service

    - name: Setup timer
      notify:
        - Restart timer
        - Reload service daemon
      ansible.builtin.copy:
        dest: /etc/systemd/system/{{ multistream_fail_over__service_name }}.timer
        src: multistream-ip-routes.timer

    - name: Setup Scripts
      notify: Restart service
      ansible.builtin.template:
        dest: /usr/local/bin/{{ item.name }}
        mode: '0775'
        src: '{{ item.src }}'
      with_items:
        - src: multistream-ip-routes.sh
          name: multistream-update-ip-routes
        - src: multistream-fail-over.py
          name: multistream-fail-over

    - name: Setup logrotate for job logs
      ansible.builtin.blockinfile:
        dest: '/etc/logrotate.conf'
        block: |
          "/var/log/multistream/_job_*" {
            hourly
            rotate 5
            compress
          }
    - name: Ensure log file is writable
      ansible.builtin.copy:
        content: ""
        dest: /var/log/multistream
        mode: '0666'

    - name: Ensure logrotate is getting run hourly
      ansible.builtin.copy:
        src: /etc/cron.daily/logrotate
        dest: /etc/cron.hourly/logrotate
        remote_src: true
