_wireguard_client__private_key: '{{ wireguard_client__private_key | mandatory }}'
_wireguard_client__local_address: '{{ wireguard_client__local_address | mandatory }}'
_wireguard_client__server_public_key: '{{ wireguard_client__server_public_key | mandatory }}'
_wireguard_client__preshared_key: '{{ wireguard_client__preshared_key | mandatory }}'
_wireguard_client__relayed_ips: '{{ wireguard_client__relayed_ips | mandatory }}'
_wireguard_client__server: '{{ wireguard_client__server | mandatory }}'

wireguard_client__interface_index: 0
wireguard_client__conf_owner: '{{ ansible_user }}'
wireguard_client__conf_owner_group: '{{ ansible_user }}'
