- name: Install chocolatey apps
  win_chocolatey:
    name: '{{ item }}'
    state: latest
  with_items:
      - 7zip
      - audacity
      - audacity-ffmpeg
      - audacity-lame
      - barrier
      - dbeaver
      - chromedriver
      - discord
      - etcher
      - ffmpeg
      - freecad
      - gimp
      - git
      - github-desktop
      - googlechrome
      - googledrive
      - gridmove
      - inkscape
      - lockhunter
      - notepadplusplus
      - obs-studio
      - putty
      - pyenv-win
      - sharex
      - shotcut
      - steam-client
      - sublimetext4
      - tightvnc
      - vlc
      - vscode
      - vscode-prettier
      - vscode-python
      - windirstat
      - winscp
      # - win32diskimager

- name: Install autohotkey
  win_chocolatey:
    name: autohotkey
    version: '1.1.31.01'
    source: https://community.chocolatey.org/api/v2/
    state: present

- import_tasks: tasks/windows_shortcuts.yml

- name: Disable startup apps
  block:
  - name: discord
    ansible.windows.win_regedit:
      path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run
      name: Discord
      data: hex:03,00,00,00,5c,13,f3,3a,97,8a,d8,01
      type: binary
  
# - name: Disable Auto startup programs
#   block:
#     - name: 
