- name: Install Docker
  notify: alpine-commit
  ansible.builtin.package:
    name:
      - docker
      - openrc
      - docker-cli-compose
    state: present

- name: Start and enable Docker
  notify: alpine-commit
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
