
- name: Install Docker
  include_role:
    name: docker

- name: Setup www root
  become: true
  block:
  - name: www root location exists
    file:
      path: /mounts/web
      state: directory
  - name: fstab file mount drive
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: UUID=63d33372-d4c8-4d9a-a042-f855c98a7e59 /mounts/web ext4 defaults 0 0
  