- name: Restart fail2ban
  ansible.builtin.systemd:
    state: restarted
    name: fail2ban
  become: true

- name: restart nginx service
  import_tasks: tasks/restart_nginx.yml

- name: certbot cert nginx
  loop: "{{ nginx_configs.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='domain') | list }}"
  become: true
  shell: "certbot register --non-interactive --nginx -d {{ item }}"
  when: enable_ssl
