- name: Install utilities
  ansible.builtin.apt:
    pkg: 
    - libnginx-mod-rtmp
    - ffmpeg
    state: present
    update_cache: true
    cache_valid_time: "{{ (12*60*60)|int }}" # 12 hr * 60 min/hr * 60 sec/min
  become: true
