- name: Install plugin
  include_tasks: '{{ ansible_os_family }}.yml'

- name: Enable rtmp
  become: true
  block:
    - name: Add to config file
      notify: restart nginx service
      ansible.builtin.blockinfile:
        marker: "# {mark} ANSIBLE CONFIG -- rtmp server"
        dest: /etc/nginx/nginx.conf
        block: "{{ lookup('template', 'rtmp_site.j2') }}"

- name: Allow RTMP through firewall
  when: not multistream_server__use_ufw
  block:
    - name: 'Firewall: Enable rtmp port'
      register: firewall_cmd_out
      ansible.posix.firewalld:
        immediate: true
        port: 1935/tcp
        permanent: true
        state: enabled

- name: Allow RTMP through firewall (ufw)
  when: multistream_server__use_ufw
  block:
    - name: 'Firewall: rtmp (ufw)'
      community.general.ufw:
        port: 1935
        rule: allow
        proto: tcp
        comment: 'Allow rtmp through firewall'
