- name: Make sure groups exist
  block:
  - name: user's group (exists)
    ansible.builtin.group:
      name: '{{ user.name }}'
  - name: user's other groups (exist)
    ansible.builtin.group:
      name: '{{ group.name }}'
    loop: '{{ user.groups }}'
    when: user.groups is defined
    loop_control:
      loop_var: group
- name: store joined groups
  ansible.builtin.set_fact:
    user_group:
    - '{{ user.name }}'
    user_groups: '{{ user.groups | default([]) | map(attribute="name") }}'
- name: Set user's groups
  ansible.builtin.user:
    groups: '{{ user_group + user_groups }}'
    name: '{{ user.name }}'
