- name: Ensure pipx is installed
  ansible.builtin.pip: # TODO: should this be apt??
    name:
      - pipx
    state: present

- name: Install certbot
  become: true
  block:
    - name: Install Core Certbot
      community.general.pipx:
        name: certbot
    - name: Install Certbot-Nginx
      community.general.pipx:
        name: certbot
        state: inject
        inject_packages:
          - certbot-nginx

- name: Register certbot
  block:
    - name: 'Certbot: create dir if needed'
      become: true
      ansible.builtin.file:
        path: /etc/letsencrypt
        state: directory
        mode: '0700'
        force: true
    - name: Register
      become: true
      ansible.builtin.shell: |
        certbot -n register --agree-tos --email {{ certbot_email }}
        touch /etc/letsencrypt/.registered
      args:
        creates: /etc/letsencrypt/.registered

- name: Setup cronjob for renewal
  become: true
  ansible.builtin.cron:
    name: certbot-renewal
    job: "/bin/bash -lc '/usr/local/bin/certbot renew >> /var/log/certbot'"
    minute: "0"
    hour: "6"
    day: "2"
