- name: Include host mapping vars
  # <vars/pubkeys.yml>
  # pubkeys:
  #   <name>: ssh-rsa <public key> <comment>
  ansible.builtin.include_vars:
    file: pubkeys.yml
    name: pubkeys

- name: Install homelab pub key
  ansible.builtin.lineinfile:
    path: ~/.ssh/authorized_keys
    line: '{{ pubkeys.pubkeys.homelab }}'
