- name: Add scripts dirs to path
  ansible.windows.win_path:
    elements:
    - "{{ item.path }}"
    scope: user
    state: present
  loop:
  - path: 'C:\bin'
  - path: 'C:\wsl_tools'
- name: create script dirs if needed
  ansible.windows.win_file:
    path: "{{ item.path }}"
    state: directory
  loop:
  - path: 'c:\bin'
  - path: 'C:\wsl_tools'
