- name: Install node
  block:
  - name: Download nvm
    block:
    - name: Download nvm-setup.exe
      ansible.windows.win_get_url:
        url: https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.exe
        dest: "{{ ansible_env.USERPROFILE }}/downloads/nvm-setup.exe"
        checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        force: false
        checksum_algorithm: sha256
    - name: Install nvm
      ansible.windows.win_shell: "{{ ansible_env.USERPROFILE }}/downloads/nvm-setup.exe /verysilent"
      args:
        creates: "{{ ansible_env.USERPROFILE }}/AppData/Roaming/nvm"
  - name: Setup node
    block:
    - name: nvm install 18.7.0
      ansible.windows.win_shell: "{{ ansible_env.USERPROFILE }}/AppData/Roaming/nvm/nvm.exe install 18.7.0"
      args:
        creates: "C:/Program Files/nodejs"
    - name: nvm use 18.7.0
      ansible.windows.win_shell: "{{ ansible_env.USERPROFILE }}/AppData/Roaming/nvm/nvm.exe use 18.7.0"
