- name: Setup ssh hosts
  block:
  - name: load ssh hosts config
    ansible.builtin.include_vars:
      file: ssh_hosts.yml
      name: ssh_hosts
  - name: Setup ssh alias scripts
    ansible.builtin.template:
      src: ../templates/ssh_script
      dest: "c:/bin/{{ item.host }}.bat"
    loop: "{{ ssh_hosts.host_info }}"
