---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-email-handler
    io.sensu.bonsai.name: sensu-email-handler
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: handler
    io.sensu.bonsai.tier: Supported
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-email-handler
    io.sensu.bonsai.version: 1.2.3
  created_by: admin
  name: sensu/sensu-email-handler
  namespace: default
  labels:
    sensu.io/workflow: sensu-flow
spec:
  builds:
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 49ee8ededc736bb6e8b9b52b8975be22408de1a6abcccc2fc8ce884f2a29f3b40816c848d89908d80cedbdba5189d63965b1daa89966417786f9a137bebb8a7b
    url: https://assets.bonsai.sensu.io/612993f29d06a66c6daf68e0d1366a725da4e9aa/sensu-email-handler_1.2.3_linux_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
    headers: null
    sha512: 5a0277013d76f5f462fa00050a1e5231f9ffb29361bb6b6084d41efdf537e01dae9c77e4f7e50adbbab56b8a9ce41587fc4cca117ef8c8c7f247f30d6d5719ac
    url: https://assets.bonsai.sensu.io/612993f29d06a66c6daf68e0d1366a725da4e9aa/sensu-email-handler_1.2.3_linux_386.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
    headers: null
    sha512: cc028608e07c3021202df728610f781b3064bbd0b2214c5a629ba6cc93b3c5b06b2667f187722c2141ef7fc844299e5def399ab0cd01b965fff43655bf50887b
    url: https://assets.bonsai.sensu.io/612993f29d06a66c6daf68e0d1366a725da4e9aa/sensu-email-handler_1.2.3_linux_arm64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'armv7'
    headers: null
    sha512: c55e14240a88889f6b068410ebee8440014d93b8862bbf74c4c07ce057190802abb8a1707a9fa68ff4e0a16cd7e2a97989b67120cf3c4724094a365b6c2e283f
    url: https://assets.bonsai.sensu.io/612993f29d06a66c6daf68e0d1366a725da4e9aa/sensu-email-handler_1.2.3_linux_armv7.tar.gz
  - filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 45247d72ccb24e34dde484f7bac137a062cace47861289012fc950debada6101f231ae49eb7c50f60e8a3087a50c643ff98873d2814439d3500c53cd9639e417
    url: https://assets.bonsai.sensu.io/612993f29d06a66c6daf68e0d1366a725da4e9aa/sensu-email-handler_1.2.3_windows_amd64.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: ae0eaec631c31ff0b04cce7ca1272cda4dddefd0738d22b73c177987034ab8756eec61c230daa96e124f986acebdd1216a5111476f75aa1f5e8d1bb1e36eb815
    url: https://assets.bonsai.sensu.io/612993f29d06a66c6daf68e0d1366a725da4e9aa/sensu-email-handler_1.2.3_darwin_amd64.tar.gz
  filters: null
  headers: null
