- name: Tempalte services file
  become: true
  block:
  - name: Make sure dir exists
    ansible.builtin.file:
      path: /usr/local/cloudflared
      state: directory
  - name: Setup compose file
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: /usr/local/cloudflared/docker-compose.yml
- name: Start service
  become: true
  community.docker.docker_compose:
    project_src: /usr/local/cloudflared
    state: present
