- name: Install build tools
  ansible.builtin.apt:
    pkg: 
    - make
    - git-all
    - build-essential
    state: latest
    update_cache: true
  become: true

- name: Install python3
  ansible.builtin.apt:
    pkg: 
    - python3
    - python3-pip
    state: latest
    update_cache: true
  become: true
