- name: Reload systemd
  become: true
  listen:
    - Rclone-timer-started
    - Rclone-service-enabled
  ansible.builtin.systemd:
    daemon_reload: true
- name: Rclone-service-enabled
  listen: Rclone-timer-started
  become: true
  ansible.builtin.systemd:
    name: '{{ rclone_backup__name | lower }}{{ rclone_backup__name_suffix }}'
    enabled: false
- name: Rclone-timer-started
  become: true
  ansible.builtin.systemd:
    name: '{{ rclone_backup__name | lower }}{{ rclone_backup__name_suffix }}.timer'
    state: started
    enabled: true
