- name: Load real_ip_from list into var
  ansible.builtin.set_fact:
    real_ip_headers_block: |
      {% for ip in nginx_real_ip_sources %}
      set_real_ip_from    {{ ip }};
      {% endfor %}
- name: Configure forwarded-for module
  notify:
    - restart nginx service
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/nginx-realip.conf
    content: |
      {{ real_ip_headers_block }}
      real_ip_header    X-Forwarded-For;
