- name: Create Update update_block_lists script
  template:
    src: update_block_lists.sh.j2
    dest: /usr/bin/update-block-lists
    owner: root
    mode: u=rwx,g=rx,o=rx
  register: update_script
- name: Setup cronjob
  cron:
    hour: '15'
    minute: '0'
    job: update-block-lists > /var/log/update_block_lists.log 2>&1
    name: Fetch latest IP block lists and apply.
