- name: Bring up service
  listen: Restart service
  become: true
  become_user: '{{ sensu_backend__service_user }}'
  community.docker.docker_compose_v2:
    project_src: '{{ sensu_backend__service_dir }}'
    state: present
    build: always
    wait: true
  register: bring_up_result


- name: Restart service
  become: true
  become_user: '{{ sensu_backend__service_user }}'
  community.docker.docker_compose_v2:
    project_src: '{{ sensu_backend__service_dir }}'
    state: present
    build: always
    wait: true
  when: not bring_up_result.changed

- name: Reload nginx
  become: true
  ansible.builtin.command:
    cmd: /usr/sbin/nginx -s reload
  changed_when: true
