# Yes, this is a round about way of doing this. The Alpine live boot (installer) does not have python in it which is required for most Ansible tasks
- name: Render the answers file on localhost /tmp
  delegate_to: localhost
  ansible.builtin.template:
    src: answers.ini.j2
    dest: /tmp/alpine-answers

- name: Slurp the file contents
  delegate_to: localhost
  ansible.builtin.slurp:
    src: /tmp/alpine-answers
  register: answers_data

- name: use builtin.raw and cat to put it on the system
  ansible.builtin.raw: |
    cat << EOF > /tmp/alpine-answers
    {{ answers_data.content | b64decode | safe }}
    EOF

- name: Setup ntp and then repo URL
  ansible.builtin.raw: |
    setup-ntp busybox && setup-apkrepos -1 && apk update

- name: Store command
  delegate_to: localhost
  ansible.builtin.set_fact:
    install_cmd: >-
      DEFAULT_DISK=none
      setup-alpine -e -f /tmp/alpine-answers 2>&1 | tee /tmp/setup-log

- name: Print command
  delegate_to: localhost
  ansible.builtin.debug:
    var: install_cmd

- name: Run the installer
  ansible.builtin.raw: '{{ install_cmd }}'
  changed_when: true

- name: Complete Alpine Diskless Installation
  ansible.builtin.raw: |
    # 1. Setup local package cache to storage
    mkdir -p {{ diskless_alpine__disk_mount_point }}/cache
    setup-apkcache {{ diskless_alpine__disk_mount_point }}/cache
    
    # 2. Commit /etc configuration overlay to storage
    lbu commit -d
  changed_when: true
