- name: Install plugin
  include_tasks: '{{ ansible_os_family }}.yml'

- name: Enable rtmp
  become: true
  block:
  - name: Add to config file
    notify: restart nginx service
    ansible.builtin.blockinfile:
      marker: "# {mark} ANSIBLE CONFIG -- rtmp server"
      dest: /etc/nginx/nginx.conf
      block: |
        rtmp {
          server {
                  listen 1935;
                  chunk_size 2048;
                  {% for ip in ALLOWED_PUBLISHERS %}
                  allow publish {{ ip }};
                  {% endfor %}
                  deny publish all;

                  application live {
                          live on;
                          record off;

                          {% for push in pushes %}
                          push {{ push }};
                          {% endfor %}

                          {% for exec in execs %}
                          exec {{ exec }};
                          {% endfor %}
                  }
              }
          }
  - name: 'firewall: Enable rtmp port'
    ansible.posix.firewalld:
      immediate: yes
      port: 1935/tcp
      permanent: yes
      state: enabled
