type: CheckConfig
api_version: core/v2
metadata:
  name: check-ssl
  namespace: default
  labels:
    sensu.io/managed_by: sensuctl
    sensu.io/workflow: sensu-flow
  annotations:
    fatigue_check/occurrences: '2' # two failures in a row
    fatigue_check/interval: '0' # do not repeat
    fatigue_check/allow_resolution: 'true'
spec:
  check_hooks: null
  command: check-ssl-host.rb -a {{ .labels.domain }} -h {{ .labels.domain }} 
  env_vars: null
  handlers:
    - influxdb
    - ntfy
    - email
    - log-handler
  high_flap_threshold: 0
  # cron: '0 16 * * *'
  interval: 30
  low_flap_threshold: 0
  output_metric_format: influxdb_line
  output_metric_handlers:
    - influxdb
  pipelines: []
  proxy_entity_name: ''
  proxy_requests:
    entity_attributes:
      - entity.entity_class == 'proxy'
      - entity.labels.proxy_type == 'website'
    splay: false
    splay_coverage: 0
  publish: true
  round_robin: true
  runtime_assets:
    - sensu-plugins/sensu-plugins-ssl
    - sensu/sensu-ruby-runtime
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
    - run_proxies
  timeout: 0
  ttl: 0
  max_output_size: 0
  discard_output: false
