type: CheckConfig
api_version: core/v2
metadata:
  name: check-http
  namespace: default
  labels:
    sensu.io/managed_by: sensuctl
    sensu.io/workflow: sensu-flow
  annotations:
    fatigue_check/occurrences: '4'
    fatigue_check/interval: '900'
    fatigue_check/allow_resolution: 'true'
spec:
  check_hooks: null
  command: http-check --url {{ .labels.url }}
  env_vars: null
  handlers:
    - influxdb
    - ntfy
    - email
    - log-handler
  high_flap_threshold: 0
  interval: 15
  low_flap_threshold: 0
  output_metric_format: influxdb_line
  output_metric_handlers:
    - influxdb
  pipelines: []
  proxy_entity_name: ''
  proxy_requests:
    entity_attributes:
      - entity.entity_class == 'proxy'
      - entity.labels.proxy_type == 'website'
    splay: false
    splay_coverage: 0
  publish: true
  round_robin: true
  runtime_assets:
    - http-checks
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
    - run_proxies
  timeout: 0
  ttl: 0
  max_output_size: 0
  discard_output: false
