type: CheckConfig
api_version: core/v2
metadata:
  name: check-status-proxy
  namespace: default
  labels:
    sensu.io/managed_by: sensuctl
    sensu.io/workflow: sensu-flow
  annotations:
    fatigue_check/occurrences: '2' # two failures in a row
    fatigue_check/interval: '0' # do not repeat
    fatigue_check/allow_resolution: 'true'
spec:
  check_hooks: null
  command: |
    output=$(curl {{ .labels.url }} 2>/dev/null )
    if [ "${output}" == *'"x - '* ]; then
            echo "Error:" >&2
            echo $(echo "${output}" | jq .) >&2
            exit 2
    elif [ "${output}" == *'"! - '* ]; then
            echo "Warning:" >&2
            echo $(echo "${output}" | jq .) >&2
            exit 1
    fi
    echo "OK:"
    echo "${output}" | jq .
  env_vars: null
  handlers:
    - influxdb
    - ntfy
    - email
  high_flap_threshold: 0
  interval: 1800 # 30 minutes * 60 s/min
  low_flap_threshold: 0
  output_metric_format: influxdb_line
  output_metric_handlers:
    - influxdb
  pipelines: []
  proxy_entity_name: ''
  proxy_requests:
    entity_attributes:
      - entity.entity_class == 'proxy'
      - entity.labels.proxy_type == 'website'
      - entity.labels.status_proxy == 'true'
    splay: false
    splay_coverage: 0
  publish: true
  round_robin: true
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
    - run_proxies
  timeout: 0
  ttl: 0
  max_output_size: 0
  discard_output: false
