---
type: Pipeline
api_version: core/v2
metadata:
  name: debounced-notifications
  namespace: default
  labels:
    provider: metrics
    sensu.io/managed_by: sensuctl
spec:
  workflows:
    - name: debounce-log
      handler:
        api_version: core/v2
        name: log-handler
        type: Handler
      mutator:
        name: debounce-message
        type: Mutator
        api_version: core/v2
    - name: debounced-ntfy
      handler:
        api_version: core/v2
        name: ntfy
        type: Handler
      mutator:
        name: debounce-message
        type: Mutator
        api_version: core/v2
      filters:
        - name: debounce-message-only
          type: EventFilter
          api_version: core/v2
    - name: debounced-email
      handler:
        api_version: core/v2
        name: email
        type: Handler
      mutator:
        name: debounce-message
        type: Mutator
        api_version: core/v2
      filters:
        - name: debounce-message-only
          type: EventFilter
          api_version: core/v2
---
type: Mutator
api_version: core/v2
metadata:
  name: debounce-message
  namespace: default
  labels:
    sensu.io/workflow: sensu-flow
spec:
  command: /opt/sensu_scripts/bin/debounce.sh
  env_vars: null
  runtime_assets:
  - jspaleta/sensu-python-runtime
  secrets: null
  timeout: 0
  type: pipe
---
type: EventFilter
api_version: core/v2
metadata:
  name: debounce-message-only
  namespace: default
  labels:
    sensu.io/managed_by: sensuctl
    sensu.io/workflow: sensu-flow
spec:
  action: allow
  expressions:
  - 'event.debounce.message != ""'
  runtime_assets: null
