- name: Install utilities
  ansible.builtin.apt:
    pkg: 
    - python3
    - python3-pip
    - nano
    - tmux
    - wget
    - curl
    - fzf
    - git
    - tree
    state: latest
    update_cache: true
  become: true
