- name: Handle Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Aliases
  become: true
  block:
  - name: ensure file exists
    copy:
      content: ""
      dest: /etc/profile.d/00-aliases.sh
      force: no
      group: sys
      owner: root
      mode: 0775
  - name: setup aliases
    ansible.builtin.lineinfile:
      line: "alias {{ item.alias}}='{{ item.cmd }}'"
      path: /etc/profile.d/00-aliases.sh
      state: present
    loop:
    - alias: fnano
      cmd: 'nano `fzf`'
  
  