- name: Render docker file
  become: true
  block:
    - name: Make sur dir exists
      ansible.builtin.file:
        path: '{{ twingate_connector_directory }}'
        state: directory
        owner: root
        group: root
        mode: '770'
    - name: Render docker file
      notify: Start service
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: '{{ twingate_connector_directory }}/docker-compose.yml'
    - name: Render env file
      notify: Start service
      ansible.builtin.copy:
        dest: '{{ twingate_connector_directory }}/.env'
        owner: root
        group: root
        mode: '770'
        content: |
          TWINGATE_ACCESS_TOKEN={{ twingate_access_token }}
          TWINGATE_REFRESH_TOKEN={{ twingate_refresh_token }}
          TWINGATE_NETWORK={{ twingate_network }}
