- name: Download setup script
  become: true
  when: twingate_access_token is defined
  block:
  - name: Make sure parent dir exits
    ansible.builtin.file:
      path: '{{ system_download_dir }}'
      state: directory
  - name: Download setup script
    register: script_download
    ansible.builtin.get_url:
      url: https://binaries.twingate.com/connector/setup.sh
      dest: '{{ system_download_dir }}/twingate_connector_setup.sh'
      mode: '0544'
      force: false # don't re-download
- name: execute_script
  when: script_download.changed or (force_tunnel_install | default(false))
  become: true
  ansible.builtin.shell:
    cmd: '{{ system_download_dir }}/twingate_connector_setup.sh'
  environment:
    TWINGATE_ACCESS_TOKEN: '{{ twingate_access_token }}'
    TWINGATE_REFRESH_TOKEN: '{{ twingate_refresh_token }}'
    TWINGATE_NETWORK: '{{ twingate_network }}'
    TWINGATE_LABEL_DEPLOYED_BY: '{{ twingate_label_deployed_by | default("linux") }}'
