- name: Setup
  when: twingate_connector_in_docker
  ansible.builtin.include_tasks:
    file: as_docker.yml
- name: Setup
  when: not twingate_connector_in_docker
  ansible.builtin.include_tasks:
    file: as_service.yml

- name: Finish handlers now
  meta: flush_handlers
