- name: Copy scripts
  become: true
  block:
    - name: Ensure destination dir exists
      ansible.builtin.file:
        state: directory
        path: '{{ sensu_backend__service_dir }}/sensu_backend_scripts'
        owner: '{{ sensu_backend__service_user }}'
        group: '{{ sensu_backend__service_user }}'
        mode: '0775'
    - name: Copy script
      ansible.builtin.copy:
        src: sensu_scripts/{{ item.src }}
        dest: '{{ sensu_backend__service_dir }}/sensu_backend_scripts/{{ item.name }}'
        owner: '{{ sensu_backend__service_user }}'
        group: '{{ sensu_backend__service_user }}'
        mode: '0775'
      loop_control:
        label: item.src
      with_items:
        - src: ntfy-send.sh
          name: ntfy-send.sh
        - src: email-send.sh
          name: email-send.sh
        - src: debounce.sh
          name: debounce.sh
