- name: Ensure user and dir exists
  become: true
  block:
    - name: Ensure user exists
      ansible.builtin.user:
        name: '{{ sensu_backend__service_user }}'
    - name: Ensure service dir exists
      ansible.builtin.file:
        path: '{{ sensu_backend__service_dir }}'
        state: directory
        owner: '{{ sensu_backend__service_user }}'
        group: '{{ sensu_backend__service_user }}'
        mode: '0770'
    - name: Ensure service config dir exists
      ansible.builtin.file:
        path: '{{ sensu_backend__service_dir }}/sensu_config'
        state: directory
        owner: '{{ sensu_backend__service_user }}'
        group: '{{ sensu_backend__service_user }}'
        mode: '0770'
    - name: Ensure user is in docker group
      ansible.builtin.user:
        name: '{{ sensu_backend__service_user }}'
        groups:
          - docker
        append: true

- name: Setup backend sensu scripts
  ansible.builtin.include_tasks: _setup_sensu_scripts.yml

- name: Setup proxy agent config
  become: true
  block:
    - name: Create proxy agent config
      ansible.builtin.template:
        dest: '{{ sensu_backend__service_dir }}/sensu_proxy_agent.yml'
        src: 'proxy_agent.yml.j2'
        owner: '{{ sensu_backend__service_user }}'
        group: '{{ sensu_backend__service_user }}'
        mode: '0664'

- name: Template out config files
  become: true
  notify: Restart service
  ansible.builtin.template:
    dest: '{{ sensu_backend__service_dir }}/{{ item.name }}'
    src: '{{ item.src | default(item.name) }}'
    owner: '{{ sensu_backend__service_user }}'
    group: '{{ sensu_backend__service_user }}'
    mode: '0664'
  with_items:
    - name: Dockerfile-backend

- name: Setup service config
  become: true
  block:
    - name: Create docker service config
      notify: Restart service
      ansible.builtin.template:
        dest: '{{ sensu_backend__service_dir }}/docker-compose.yaml'
        src: 'docker-compose.yaml'
        owner: '{{ sensu_backend__service_user }}'
        group: '{{ sensu_backend__service_user }}'
        mode: '0664'
    - name: Ensure variables in env file
      notify: Restart service
      ansible.builtin.blockinfile:
        # NOTE: admin credentionals do NOT have role defaults and must be set as host or group var.
        block: |
          SENSU_BACKEND_CLUSTER_ADMIN_USERNAME={{ sensu_backend__admin_username }}
          SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD='{{ sensu_backend__admin_password }}'
        path: '{{ sensu_backend__service_dir }}/.env'
        create: true
        owner: '{{ sensu_backend__service_user }}'
        group: '{{ sensu_backend__service_user }}'
        mode: '0660'

- name: Bring up container now
  ansible.builtin.meta: flush_handlers

- name: Setup http checks
  ansible.builtin.include_tasks: _setup_http_checks.yml

- name: Copy nginx server template
  notify: Reload nginx
  become: true
  ansible.builtin.template:
    src: 'nginx-site.j2'
    dest: /etc/nginx/sites-enabled/sensu
    owner: root
    group: root
    mode: '0664'
