- name: System up to date
  hosts: data-buddy
  roles:
    - role: system_up_to_date
      sub_task: sync_repo
    - role: system_up_to_date
      sub_task: setup_schedule
    - role: system_up_to_date

- name: Setup Users
  hosts: data-buddy
  roles:
    - name: users_managed

- name: Local shares
  hosts: data-buddy
  vars:
    ufw_configured_allowed_apps: '{{ data_buddy_allowed_ufw_apps | default(["https"]) }}'
  roles:
    - name: user_sanity_tools_installed
    - name: data_buddy
      sub_task: _idempotent_format_drives
    - name: data_buddy
      sub_task: _smb_share
    - name: data_buddy
      when: data_buddy_use_immich | default(true)
      sub_task: _setup_immich
    - name: data_buddy
      sub_task: _config_rclone
    - name: ufw_allow_ssh_on_docker # and explicitly disallow anything that's not allowed
