---

- hosts: homelab_proxy
  vars:
    nginx_config_dir: /etc/nginx/sites-available
    nginx_link_dir: /etc/nginx/sites-enabled
  
  # tasks:
  # - name: Include host mapping vars
  #   ansible.builtin.include_vars:
  #     file: 
  #   include_tasks: certbot_register_domain.yml

  roles:
  - role: linux_core
  - role: nginx
  - role: homelab_proxy
  # certbot??
  # https://github.com/geerlingguy/ansible-role-certbot

  tasks:
  - name: include proxy info
    ansible.builtin.include_vars:
      file: homelab_proxy_sites.yml
      name: proxy
  - name: setup gitea hosts
    ansible.builtin.include_tasks: tasks/gitea.yml
    loop: "{{ proxy.sites | selectattr('gitea_config_dir', 'defined') }}"
