---

- name: Configure nginx servers
  hosts: nginx
  roles:
  - role: nginx
- name: Configure nginx servers
  hosts: nginx_minimal
  roles:
  - role: nginx_minimal
- name: Windows settings
  hosts: windows
  roles:
  - chocolatey
  - pyenv-win
  - putty
  tasks:
    - ansible.builting.import_tasks: tasks/taskbar.yml
    - ansible.builting.import_tasks: tasks/path.yml
    - ansible.builting.import_tasks: tasks/vscode.yml
    - ansible.builting.import_tasks: tasks/windows_scripts.yml
    - ansible.builting.import_tasks: tasks/windows_shortcuts.yml
    - ansible.builting.import_tasks: tasks/windows_dev.yml
