---

- name: Windows settings
  hosts: windows
  roles:
  - chocolatey
  - pyenv-win
  - putty
  tasks:
  - import_tasks: tasks/taskbar.yml
  - import_tasks: tasks/path.yml
  - import_tasks: tasks/vscode.yml
  - import_tasks: tasks/windows_scripts.yml
  - import_tasks: tasks/windows_shortcuts.yml
  - import_tasks: tasks/windows_dev.yml
