---

- name: Configure multistream servers
  hosts: multistream_failover
  roles:
    - role: users_managed
    - role: sshd_configured
    - role: group_allowed_commands
    - role: multistream_fail_over
