- name: Setup tpm unlocked booting with VPN tunnel
  hosts:
    - drives_unlock_with_tpm2
  roles:
    - drives_unlock_with_tpm2
    - role: system_up_to_date
      sub_task: sync_repo
    - role: system_up_to_date
      sub_task: setup_schedule
    - role: system_up_to_date
    - users_managed

- name: Setup VPN tunnel
  hosts:
    - twingate_tunnels
  roles:
    - twingate
