---

- name: Install and setup certbot
  hosts: certbot

  roles:
  - certbot_installed

  tasks:
  
  - name: Setup certs
    block:
      - name: Load certs file
        ansible.builtin.include_vars:
          file: certbot_managed_certs.yml
          name: certs1
      - name: Get cert {{ item.name }} (automatic)
        ansible.builtin.command:
          cmd: /root/.local/bin/certbot certonly -d {{ item.name }}
        when: not item.get('private_challenge')
        loop: '{{ certs1.domains }}'
      - name: Get cert {{ item.name }} (acme challenge)
        ansible.builtin.shell:
          cmd: >
            /root/.local/bin/certbot certonly
            -v
            --manual --manual-auth-hook /etc/letsencrypt/acme-dns-auth.py
            --preferred-challenges dns 
            --debug-challenges
            -d {{ item.name }} | tee /var/tmp/certbot_output_{{ my_index }}
        args:
          creates: /etc/letsencrypt/live/{{ item.name.strip('*.') }}/privkey.pem
        when: item.get('private_challenge')
        loop: '{{ certs1.domains }}'
        loop_control:
          index_var: my_index
