- name: Setup twingate tunnels
  hosts: twingate_tunnels
  roles:
  - twingate
- name: Setup clodflare tunnels
  hosts: cloudflare_docker_tunnels
  roles:
  - docker
  - role: cloudflare_tunnel
    using_docker: yes
- name: Setup system updates
  hosts:
  - twingate_tunnels
  - cloudflare_docker_tunnels
  roles:
  - system_up_to_date
  - role: system_up_to_date
    sub_task: setup_schedule
