- name: Handle Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Disable systemd-resolved
  become: true
  ansible.builtin.block:
  - name: Stop and disable systemd-resolved
    ansible.builtin.systemd:
      name: systemd-resolved
      state: stopped
      enabled: no
  # from https://fabianlee.org/2021/03/02/ansible-deleting-a-file-path-but-only-if-a-symbolic-link/
  - stat:
    path: /etc/resolv.conf
    register: link
  - name: remove symlink resolv.conf
    file:
      path: /etc/resolv.conf
      state: absent
    when: link.stat.islnk is defined and link.stat.islnk
  - name: Touch resolv.conf
    file:
      path: /etc/resolv.conf
      state: touch

- name: Set IP if not provided
  ansible.builtin.set_fact:
    ip_address: "{{ ip | default('10.20.23.0') }}"

- name: Set start of IP range
  block:
  - ansible.builtin.set_fact:
      ip_range_start__prefix: "{{ ip_address.split('.')[0:3] | join('.') }}"
  - ansible.builtin.set_fact:
      ip_range_start__suffix: "{{ int(ip_address.split('.')[-1]) + 1 }}"
  - ansible.builtin.set_fact:
      ip_range_start: "{{ ip_range_start__prefix -}} . {{- ip_range_start__suffix }}"


- name: Config dnsmasq dhcp server
  ansible.builtin.copy:
    file: /etc/dnsmasq.d/dhcp
    content: |
      # Only operate on eth0
      interface=eth0

      dhcp-range={{ ip_range_start -}} , {{- ip_range_start__prefix }}.255,255.255.255.0,6h
  notify: Restart dnsmasq
