- name: Run updates
  become: yes
  block:
    - name: Run system updates
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
    - name: Check if reboot required 
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_flag_file
- name: Reboot system
  become: yes
  when: reboot_flag_file.stat.exists
  block:
    - name: Update grub config
      ansible.builtin.command: 
        cmd: update-grub
    - name: Reboot system
      when: not reboot_controller
      ansible.builtin.reboot:
    - name: Reboot system (shell)
      when: reboot_controller
      ansible.builtin.shell:
        cmd: reboot now
