on:
    push:
      branches:
        - main
      paths:
        - playbooks/roles/system_up_to_date/**
        - .github/workflows/upstate-system-update-repo.yml
    workflow_dispatch:

jobs:
  trigger_update:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CLIENT_PUBLISH_PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'mshafer1',
              repo: 'system_updater',
              workflow_id: 'ci.yml',
              ref: 'main'
            });
