on:
    push:
      branches:
        - main
      paths:
        - playbooks/roles/system_up_to_date/**
    workflow_dispatch:

jobs:
  trigger_update:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              'mshafer',
              'system_updater',
              'workflows/ci.yml',
              'main',
            });
