on:
    push:
      branches:
        - main
      paths:
        - playbooks/roles/system_up_to_date/**
        - .github/workflows/update-system-update-repo.yml
    workflow_dispatch:

jobs:
  trigger_update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout other repo
        uses: actions/checkout@v3
        with: 
          repository: mshafer1/system_updater.git
          ref: main
      - name: Trigger workflow
        run: |
          gh workflow --help
          gh workflow run ci.yml
        env:
          GH_TOKEN: ${{ secrets.CLIENT_PUBLISH_PAT_TOKEN }}
