- name: Handle OS based items
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Check for XZ CVE
  ansible.builtin.include_tasks: check_for_cve.yml

- name: Firewall configs (firewalld)
  become: true
  when: use_firewalld | bool
  block:
    - name: 'Firewall: permit traffic in default zone services'
      ansible.posix.firewalld:
        service: '{{ item }}'
        permanent: true
        state: enabled
      when: enable_public_web | bool
      with_items:
        - http
        - https

    - name: 'Firewall: Enable ssh port'
      ansible.posix.firewalld:
        port: '{{ SSH_PORT }}/tcp'
        permanent: true
        state: enabled

- name: Firewall configs (ufw)
  become: true
  when: not (use_firewalld | bool)
  block:
    - name: Deny everything and enable UFW
      community.general.ufw:
        state: enabled
        default: reject
    - name: 'Firewall: Enable ssh port'
      community.general.ufw:
        port: '{{ SSH_PORT }}'
        rule: allow
        proto: tcp
        comment: 'Allow SSH connections on port {{ SSH_PORT }}'
    - name: 'Firewall: permit traffic in default zone services'
      community.general.ufw:
        app: '{{ item }}'
        policy: allow
      when: enable_public_web | bool
      with_items:
        - http
        - https
