- name: Handle OS based items
  ansible.builtin.include_tasks: '{{ ansible_os_family }}.yml'

- name: Firewall configs
  become: true
  block:
    - name: 'Firewall: permit traffic in default zone services'
      ansible.posix.firewalld:
        service: '{{ item }}'
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - http
        - https

    - name: 'Firewall: Enable ssh port'
      ansible.posix.firewalld:
        port: '{{ SSH_PORT }}/tcp'
        permanent: true
        immediate: true
        state: enabled

- name: Setup certbot
  ansible.builtin.include_tasks: certbot.yml
