- name: Handle OS based items

- name: Check for XZ CVE
  ansible.builtin.include_tasks: check_for_cve.yml

- name: Firewall configs
  become: true
  block:
    - name: 'Firewall: permit traffic in default zone services'
      ansible.posix.firewalld:
        service: '{{ item }}'
        permanent: true
        state: enabled
      with_items:
        - http
        - https

    - name: 'Firewall: Enable ssh port'
      ansible.posix.firewalld:
        port: '{{ SSH_PORT }}/tcp'
        permanent: true
        state: enabled
