- name: Handle OS based items
  include_tasks: '{{ ansible_os_family }}.yml'

- name: Firewall configs
  become: true
  block:
  - name: 'firewall: permit traffic in default zone services'
    ansible.posix.firewalld:
      service: '{{ item }}'
      permanent: yes
      state: enabled
    with_items:
    - http
    - https

  - name: 'firewall: Enable ssh port'
    ansible.posix.firewalld:
      port: '{{ SSH_PORT }}/tcp'
      permanent: yes
      state: enabled
